name: Check Markdown links

on: 
  schedule:
    - cron: '55 23 2,17 * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        base-branch: 'main'
        config-file: '.github/workflows/.check_markdown_links_config.json'